spring:
  application:
    name: login
  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: root