spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/authentification
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/liquibase.xml